In [ ]:
# check which gpu we're using
!nvidia-smi

Sat Mar 19 09:08:42 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P0    27W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
!tar -xf bert-8-3-5.tar.gz
# !unzip data.csv.zip

In [ ]:
!pip install transformers
!pip install pytorch-pretrained-bert
!pip install torch

     |████████████████████████████████| 3.8 MB 6.9 MB/s 
     |████████████████████████████████| 596 kB 15.7 MB/s 
     |████████████████████████████████| 6.5 MB 52.4 MB/s 
     |████████████████████████████████| 67 kB 5.4 MB/s 
     |████████████████████████████████| 895 kB 43.6 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
     |████████████████████████████████| 123 kB 4.2 MB/s 
     |████████████████████████████████| 132 kB 9.2 MB/s 
     |████████████████████████████████| 8.6 MB 9.3 MB/s 
     |████████████████████████████████| 79 kB 8.5 MB/s 
     |████████████████████████████████| 138 kB 62.7 MB/s 
     |████████████████████████████████| 127 kB 71.6 MB/s 
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3
ERROR: pip's dependency resolver does not currently take into 

In [ ]:
# # helper function to save predictions to an output file
# def labels2file(p, outf_path):
# 	with open(outf_path,'w') as outf:
# 		for pi in p:
# 			outf.write(','.join([str(k) for k in pi])+'\n')

# Load Data

In [ ]:
import pandas as pd
from collections import Counter

In [ ]:
df = pd.read_csv('2021_Q1_2.csv', lineterminator='\n')
len(df)

217831

In [ ]:
df

Unnamed: 0  Unnamed: 0.1            author id  \
0                0             0           2906869757   
1                1             1             74529629   
2                2             2             38971530   
3                3             3  1335905820232409094   
4                4             4           3096702665   
...            ...           ...                  ...   
217826      217826        217826             14189166   
217827      217827        217827  1069362780464193536   
217828      217828        217828           2251770488   
217829      217829        217829   814490080815579136   
217830      217830        217830            574807922   

                       created_at                   id lang  like_count  \
0       2021-03-31 23:59:58+00:00  1377410373607858177   en          18   
1       2021-03-31 23:59:47+00:00  1377410327248171010   en           5   
2       2021-03-31 23:59:44+00:00  1377410315340632068   en           0   
3       2021-03-31 23:58:52+00:00  1377410094191706113   en           1   
4       2021-03-31 23:58:50+00:00  1377410089049415683   en           0   
...                           ...                  ...  ...         ...   
217826  2021-01-01 00:02:48+00:00  1344796177447985153   en           0   
217827  2021-01-01 00:02:20+00:00  1344796059747426305   en           5   
217828  2021-01-01 00:02:01+00:00  1344795980475076613   en           1   
217829  2021-01-01 00:01:16+00:00  1344795793644007425   en           1   
217830  2021-01-01 00:00:01+00:00  1344795476604956673   en           4   

        quote_count  reply_count  retweet_count               source  \
0                 0            2             14      Twitter Web App   
1                 0            0              3   Twitter for iPhone   
2                 0            0              0             Paper.li   
3                 0            0              1   Twitter for iPhone   
4                 0            1              0  Jenkers Eng Posting   
...             ...          ...            ...                  ...   
217826            0            1              0   Twitter for iPhone   
217827            0            0              3  Twitter for Android   
217828            0            0              0           Oz History   
217829            0            0              0       Hootsuite Inc.   
217830            1            1              0            TweetDeck   

                                                    tweet  \
0       Latest  #takeaway with @ElizHagedorn @joesnell...   
1       China before Buddhism: a class lecture on the ...   
2       The latest The Political Science Daily! https:...   
3       Mar30-#Karaj,#Iran\nLocals have gathered for t...   
4       UN is warned to prevent 'civil war' in #Myanma...   
...                                                   ...   
217826  So...why are we supposed to be upset about for...   
217827  Emma Alam competed and won 29th World Memory C...   
217828  Today, in 1851 - #Melbourne�s #China Town was ...   
217829  China orders Alibaba founder Jack Ma to pare d...   
217830  #FromTheRight: Here Are The Companies Linked T...   

        CARDIFFNLP_ROBERTA_PREDS  hateXplain_PREDS  
0                              0                 1  
1                              0                 1  
2                              0                 1  
3                              0                 1  
4                              0                 1  
...                          ...               ...  
217826                         0                 1  
217827                         0                 1  
217828                         0                 1  
217829                         0                 1  
217830                         0                 1  

[217831 rows x 14 columns]

In [ ]:
tweets = df.tweet

# Predict

In [10]:
!python run-bert.py --input 2021_Q1_2.csv --output 2021_Q1.csv --gpu 0 --trainedBertModel ./bert-8-3-5

There are 1 GPU(s) available.
We will use the GPU: Tesla P100-PCIE-16GB
Downloading: 100% 226k/226k [00:00<00:00, 1.03MB/s]
Downloading: 100% 28.0/28.0 [00:00<00:00, 21.3kB/s]
Downloading: 100% 570/570 [00:00<00:00, 401kB/s]
/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:2277: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  FutureWarning,
Predicting labels for 217,831 test sentences...
Using GPU cuda:0
 13% 27229/217831 [53:09<6:12:08,  8.54it/s]
    DONE.
[0 0 0 ... 0 0 0]
 13% 27229/217831 [53:09<6:12:08,  8.54it/s]
    DONE.
[0 0 0 ... 0 0 0]


In [11]:
df1 = pd.read_csv('2021_Q1.csv', lineterminator='\n')

In [12]:
Counter(df1['COVID_HATE_BERT_PREDS'])

Counter({0: 214505, 1: 681, 2: 2645})

In [13]:
from google.colab import files
files.download('2021_Q1.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [14]:
!python run-bert.py --input 2021_Q2_2.csv --output 2021_Q2.csv --gpu 0 --trainedBertModel ./bert-8-3-5

There are 1 GPU(s) available.
We will use the GPU: Tesla P100-PCIE-16GB
/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:2277: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  FutureWarning,
Predicting labels for 232,949 test sentences...
Using GPU cuda:0
 13% 29119/232949 [57:25<6:41:57,  8.45it/s]
    DONE.
[0 0 0 ... 0 0 0]


In [15]:
df2 = pd.read_csv('2021_Q2.csv', lineterminator='\n')
Counter(df2['COVID_HATE_BERT_PREDS'])

Counter({0: 228716, 1: 648, 2: 3585})

In [ ]:
files.download('2021_Q2.csv')

In [17]:
!python run-bert.py --input 2021_Q3_2.csv --output 2021_Q3.csv --gpu 0 --trainedBertModel ./bert-8-3-5

There are 1 GPU(s) available.
We will use the GPU: Tesla P100-PCIE-16GB
/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:2277: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  FutureWarning,
Predicting labels for 243,974 test sentences...
Using GPU cuda:0
 13% 30497/243974 [1:00:10<7:01:16,  8.45it/s]
    DONE.
[0 0 0 ... 0 0 0]


In [18]:
df3 = pd.read_csv('2021_Q3.csv', lineterminator='\n')
Counter(df3['COVID_HATE_BERT_PREDS'])

Counter({0: 240987, 1: 454, 2: 2533})

In [ ]:
files.download('2021_Q3.csv')

In [20]:
!python run-bert.py --input 2021_Q4_2.csv --output 2021_Q4.csv --gpu 0 --trainedBertModel ./bert-8-3-5

There are 1 GPU(s) available.
We will use the GPU: Tesla P100-PCIE-16GB
/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:2277: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  FutureWarning,
Predicting labels for 241,244 test sentences...
Using GPU cuda:0
 13% 30156/241244 [58:50<6:51:49,  8.54it/s]
    DONE.
[0 0 0 ... 0 0 0]


In [21]:
df4 = pd.read_csv('2021_Q4.csv', lineterminator='\n')
Counter(df4['COVID_HATE_BERT_PREDS'])

Counter({0: 238598, 1: 394, 2: 2252})

In [22]:
files.download('2021_Q4.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>